### PR TITLE
updated bins line 954

### PR DESCRIPTION
**Pull request by MaxSokolich**

### CODE REVIEW

**Review by dorenboschm — COMMENTED** [review]
Why?

**Comment by MaxSokolich** [comment]
no idea. just wanted to create a pull request

**Comment by dorenboschm** [comment]
I appreciate it

**Comment by dorenboschm** [comment]
Not gonna lie; I'm trying to do a pull request on yours but completely forgot how to. I forked your modern machine learning and made a change. What do I do next?

**Comment by MaxSokolich** [comment]
I dont think you need to fork it. Litterally just make a change on a file by clicking the edit button in the top right. Once yuouve edited something scroll down to the bottom and youll see commit changes. Then theyll be another green button that says create pull request or something

**Comment by MaxSokolich** [comment]
or maybe it forks it automatically when you edit something im not completely sure tbh

**Comment by dorenboschm** [comment]
I guess forking it allows you to run all the files on your computer locally maybe

**Pull request closed without merging**
